server {
    listen 8080;

    location /api/ {
        proxy_pass https://preevent-backend-46365571298.asia-east1.run.app;
        proxy_set_header Host preevent-backend-46365571298.asia-east1.run.app;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri.html $uri/ /index.html;
    }
}
